language: node_js
node_js:
- stable
- '6'
- '5'
before_install:
- npm install -g codecov
script:
- npm test && codecov
notifications:
  email: false
deploy:
  provider: npm
  email: aokiken@me.com
  on:
    tags: true
  api_key:
    secure: wbcyC/AGQqItv51HQoD6un5eOejzOlSiTsx95GnvekuAfaQDXhgc/DxSlzHTQvNY2B3yAlZKKa2KKbuozGWDCK1Y6GpqQTHcRP6M6zmOqXHYeX1gFM9i1oBqMUjN0n68AFpJ4E71eWhwF6DQvuLpegc4iMyC+8OprXg2Gi45hCizoZ3JBho0Gkvi+HedZYZ2uciByiJ6Cs1++axSpIrs3NEDYIwrLkU6HkF3vBvzpFXGve7Ou0o45QEj460ZRMGy7/Ag8SF4uecBItH0lUuL/FYfAoUsgZ2UNZ1fZXKYkODBQQQL+qC6BA+23/eiLVpAVcNacrUOwEQKORC/L4kyN/0/uIgsS0RCPRSjkK/m65CIxrswtwkg9XGl/WkOIjSfmlpVlPFfb+CL3vly6CRM+fSExH7QaVY90SUfsqrLEh2WJmMEBEXI0YwR6e+GeZ3mypVepzqZQ9UyYlxolEqknibxuJH9u75UyOusWjRk9Ly6oUbKUT1SUK2fAAVE8QCnyIoaz5qWUV0VbWYaAnvo6qybTlowo7iIiyaRKkHa22wFBJYTTkHHHs4sbNhirD+C+WOjF/GipTupz21SP3WVOFjvW+bIKD74nNT+avoufX2hMhJVqMMKzWCZJLxJ84aHnSh8KdNKLDSQg9BH2DQbjqX9QtbN3q/KiHkUQNMsVS0=
